name: beebase
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.7
  flutter_config:
    path: plugins/flutter_config
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  path_provider: ^2.1.5
  get_it: ^8.0.3
  auto_route: ^11.1.0
  flutter_bloc: ^8.1.6
  json_annotation: ^4.9.1
  flutter_secure_storage: ^9.2.4
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  liquid_glass_widgets:
    path: plugins/liquid_glass_widgets
  geolocator: ^14.0.2
  geocoding: ^5.0.0
  fl_chart: ^1.2.0
  path: ^1.9.1
  image_picker: ^1.2.3
  package_info_plus: ^8.1.1
  qr_flutter: ^4.1.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.0
  auto_route_generator: ^10.6.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  path_provider_platform_interface: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/langs/
  fonts:
    - family: RobotoSlab-Bold
      fonts:
        - asset: assets/fonts/RobotoSlab/RobotoSlab-Bold.ttf
          weight: 700
    - family: RobotoSlab-Regular
      fonts:
        - asset: assets/fonts/RobotoSlab/RobotoSlab-Regular.ttf
          weight: 400
    - family: IBMPlexSans-Bold
      fonts:
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-Bold.ttf
          weight: 700
    - family: IBMPlexSans-Regular
      fonts:
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-Italic.ttf
          weight: 400
          style: italic
